# Generated by Django 5.0.6 on 2024-07-18 09:56

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='posts/', validators=[posts.models.validate_media_type]),
        ),
    ]
