# Generated by Django 5.0.6 on 2024-08-09 10:14

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Commentary', 'verbose_name_plural': 'Commentaries'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(null=True, upload_to='posts/', validators=[posts.models.validate_media_type]),
        ),
    ]
