# Generated by Django 5.0.6 on 2024-08-09 10:16

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_commentary_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='posts/', validators=[posts.models.validate_media_type]),
        ),
    ]
