# Generated by Django 5.0.6 on 2024-07-18 09:54

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chats/', validators=[chats.models.validate_media_type]),
        ),
    ]
